### ISSUE TITLE
LongArch64 support is merged to .NET 7 main

### ISSUE THREAD

**Issue by driver1998** [xen0n/xen0n.github.io#13]
https://github.com/dotnet/runtime/pulls?q=is%3Aopen+is%3Apr+label%3Aarch-loongarch64

No ready to use fork however, I guess one can get a usable build by manually merging all the PRs?

**Comment by xen0n** [comment]
Hmm let me adjust later in the evening.

Thanks for the heads-up!

**Comment by driver1998** [comment]
https://hub.fastgit.xyz/dotnet/runtime/issues/59561#issuecomment-1108987060
https://hub.fastgit.xyz/dotnet/runtime/pulls?q=is%3Apr+label%3Aarch-loongarch64+is%3Aclosed

LongArch64 support is merged to .NET 7 main.

**Comment by xen0n** [comment]
Holy sh*t, none of them contacted me for reviews... I'd edit the document then.

**Comment by xen0n** [comment]
Updated.
